// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: config/recent_activity.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecentActivityEntryType int32

const (
	RecentActivityEntryType_ENTRY_TYPE_UNSPECIFIED RecentActivityEntryType = 0
	RecentActivityEntryType_ENTRY_TYPE_TASK        RecentActivityEntryType = 1
	RecentActivityEntryType_ENTRY_TYPE_PROJECT     RecentActivityEntryType = 2
)

// Enum value maps for RecentActivityEntryType.
var (
	RecentActivityEntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_TASK",
		2: "ENTRY_TYPE_PROJECT",
	}
	RecentActivityEntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"ENTRY_TYPE_TASK":        1,
		"ENTRY_TYPE_PROJECT":     2,
	}
)

func (x RecentActivityEntryType) Enum() *RecentActivityEntryType {
	p := new(RecentActivityEntryType)
	*p = x
	return p
}

func (x RecentActivityEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecentActivityEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_recent_activity_proto_enumTypes[0].Descriptor()
}

func (RecentActivityEntryType) Type() protoreflect.EnumType {
	return &file_config_recent_activity_proto_enumTypes[0]
}

func (x RecentActivityEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// RecentActivityConfig represents the on-disk recent activity configuration.
type RecentActivityConfig struct {
	state              protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*RecentActivityEntry `protobuf:"bytes,1,rep,name=entries,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecentActivityConfig) Reset() {
	*x = RecentActivityConfig{}
	mi := &file_config_recent_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentActivityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentActivityConfig) ProtoMessage() {}

func (x *RecentActivityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_recent_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecentActivityConfig) GetEntries() []*RecentActivityEntry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *RecentActivityConfig) SetEntries(v []*RecentActivityEntry) {
	x.xxx_hidden_Entries = &v
}

type RecentActivityConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*RecentActivityEntry
}

func (b0 RecentActivityConfig_builder) Build() *RecentActivityConfig {
	m0 := &RecentActivityConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

// RecentActivityEntry represents a single recent activity item.
type RecentActivityEntry struct {
	state                   protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Type         RecentActivityEntryType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.RecentActivityEntryType"`
	xxx_hidden_TaskId       string                  `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_LastActivity *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=last_activity,json=lastActivity,proto3"`
	xxx_hidden_Source       string                  `protobuf:"bytes,4,opt,name=source,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RecentActivityEntry) Reset() {
	*x = RecentActivityEntry{}
	mi := &file_config_recent_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentActivityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentActivityEntry) ProtoMessage() {}

func (x *RecentActivityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_config_recent_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecentActivityEntry) GetType() RecentActivityEntryType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return RecentActivityEntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *RecentActivityEntry) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *RecentActivityEntry) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastActivity
	}
	return nil
}

func (x *RecentActivityEntry) GetSource() string {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return ""
}

func (x *RecentActivityEntry) SetType(v RecentActivityEntryType) {
	x.xxx_hidden_Type = v
}

func (x *RecentActivityEntry) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *RecentActivityEntry) SetLastActivity(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastActivity = v
}

func (x *RecentActivityEntry) SetSource(v string) {
	x.xxx_hidden_Source = v
}

func (x *RecentActivityEntry) HasLastActivity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastActivity != nil
}

func (x *RecentActivityEntry) ClearLastActivity() {
	x.xxx_hidden_LastActivity = nil
}

type RecentActivityEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type         RecentActivityEntryType
	TaskId       string
	LastActivity *timestamppb.Timestamp
	Source       string
}

func (b0 RecentActivityEntry_builder) Build() *RecentActivityEntry {
	m0 := &RecentActivityEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_LastActivity = b.LastActivity
	x.xxx_hidden_Source = b.Source
	return m0
}

var File_config_recent_activity_proto protoreflect.FileDescriptor

const file_config_recent_activity_proto_rawDesc = "" +
	"\n" +
	"\x1cconfig/recent_activity.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\x14RecentActivityConfig\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.proto.RecentActivityEntryR\aentries\"\xbb\x01\n" +
	"\x13RecentActivityEntry\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.proto.RecentActivityEntryTypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12?\n" +
	"\rlast_activity\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source*b\n" +
	"\x17RecentActivityEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fENTRY_TYPE_TASK\x10\x01\x12\x16\n" +
	"\x12ENTRY_TYPE_PROJECT\x10\x02B6Z4github.com/devplaninc/devplan-cli/internal/pb/configb\x06proto3"

var file_config_recent_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_recent_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_recent_activity_proto_goTypes = []any{
	(RecentActivityEntryType)(0),  // 0: proto.RecentActivityEntryType
	(*RecentActivityConfig)(nil),  // 1: proto.RecentActivityConfig
	(*RecentActivityEntry)(nil),   // 2: proto.RecentActivityEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_config_recent_activity_proto_depIdxs = []int32{
	2, // 0: proto.RecentActivityConfig.entries:type_name -> proto.RecentActivityEntry
	0, // 1: proto.RecentActivityEntry.type:type_name -> proto.RecentActivityEntryType
	3, // 2: proto.RecentActivityEntry.last_activity:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_recent_activity_proto_init() }
func file_config_recent_activity_proto_init() {
	if File_config_recent_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_recent_activity_proto_rawDesc), len(file_config_recent_activity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_recent_activity_proto_goTypes,
		DependencyIndexes: file_config_recent_activity_proto_depIdxs,
		EnumInfos:         file_config_recent_activity_proto_enumTypes,
		MessageInfos:      file_config_recent_activity_proto_msgTypes,
	}.Build()
	File_config_recent_activity_proto = out.File
	file_config_recent_activity_proto_goTypes = nil
	file_config_recent_activity_proto_depIdxs = nil
}
