name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git URL
        run: git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Get dependencies
        run: go mod tidy

      - name: Build for multiple platforms
        run: |
          # Get version from tag (without 'v' prefix)
          export VERSION=${GITHUB_REF#refs/tags/v}
          echo "CLI_VERSION=${VERSION}" >> $GITHUB_ENV
          export COMMIT_HASH=$(git rev-parse HEAD)
          export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          ./scripts/build_all.sh

      - name: Upload to DigitalOcean Spaces
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_KEY }}
        run: |
          aws --endpoint-url https://sfo3.digitaloceanspaces.com \
            s3 cp build/ \
            s3://devplan-cli.sfo3.digitaloceanspaces.com/releases/versions/${{ env.CLI_VERSION }}/ \
            --recursive

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain
