name: Test Build

on:
  push:
    branches:
      - '**'

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git URL
        run: git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests
        run: make test

      - name: Build CLI
        run: |
          export COMMIT_HASH=$(git rev-parse HEAD)
          export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          make build

      - name: Verify build with version command
        run: |
          ./out/devplan-cli version
